spring:
  data:
    cassandra:
      keyspace-name: bootcamp
      username: NUhLATNGBOjvjkUPNNqHrvUj
      password: 6378wbFznhn7ru5ZKxIhJTchiMv0hEgmbRZkYejmAXzUZh.R,6ErJjPGuynMTYs8PLDfqKW.00LZfP5H_uQ7mQxDHCsjdpU94r1YA+_Pck1Cvb,32+6MOruC-SKcqdFZ
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
#  kafka:
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      auto-offset-reset: earliest
#      properties:
#        spring:
#          json:
#            use:
#              type:
#                headers: 'false'
#            value:
#              default:
#                type: com.springReactive.employeeService.model.EmployeeRequest
#      group-id: reactivekafkaconsumerandproducer
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    bootstrap-servers: localhost:9200
#    properties:
#      spring:
#        json:
#          trusted:
#            packages: '*'
datastax.astra:
  secure-connect-bundle: secure-connect-employee.zip

astra.db:
  id: 1125ef20-5307-4510-b578-d834a6c79178-1
  region: asia-south1
  keyspace: bootcamp
  application.token: AstraCS:NUhLATNGBOjvjkUPNNqHrvUj:26e16eba1a17100d4a0c782127bafcd5f3bcc86ce271979c1b1b7a1a32d70ca5

server:
  port: 8081

PRODUCER_TOPIC: app_updates
CONSUMER_TOPIC: app_updates
